In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import os
import torch
torch.cuda.is_available()

C:\Users\Jo\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


True

In [8]:
print("Version of Tensorflow: ", tf.__version__)
print("Cuda Availability: ", tf.test.is_built_with_cuda())
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Version of Tensorflow:  2.13.1
Cuda Availability:  False
Num GPUs Available:  0


In [9]:
pip list

Package                       Version
----------------------------- ------------
absl-py                       2.1.0
alabaster                     0.7.12
anyio                         3.6.2
argcomplete                   1.10.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
asn1crypto                    1.5.1
asttokens                     2.2.1
astunparse                    1.6.3
async-generator               1.10
atomicwrites                  1.4.1
attrs                         22.2.0
Babel                         2.11.0
backcall                      0.2.0
beautifulsoup4                4.8.2
black                         22.12.0
bleach                        5.0.1
cachetools                    5.3.3
certifi                       2022.12.7
cffi                          1.15.1
chardet                       3.0.4
charset-normalizer            2.1.1
click                         8.1.3
coincurve                     18.0.0
colora

In [10]:
path = "data_0_cloned"

data = []
for file in os.listdir(path):
    f = open(os.path.join(path,file), "r")
    s = f.read()
    d = [int(x) for x in s]
    data.append(d)

# randomized categories
categories = list(np.random.randint(low = 3,size=50))

In [5]:
categories

[1,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 0,
 2,
 2,
 2,
 0,
 0,
 2,
 2,
 1,
 1,
 0,
 0,
 0,
 2,
 0,
 2,
 2,
 0,
 1,
 1,
 0,
 2,
 1,
 2,
 1,
 0,
 1,
 2,
 2,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 0,
 1,
 1,
 1,
 0,
 2]

In [11]:
data = np.array(data)
categories = np.array(categories)

X_train, x_test, y_train, y_test = train_test_split(data, categories, test_size=0.2, random_state=42)

In [14]:
y_train = np.transpose(y_train)
y_train.shape
size = X_train.shape[1]
y_train

array([1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 2, 1, 0, 2, 1, 2, 0, 2, 0, 0, 2, 2,
       0, 2, 0, 1, 0, 1, 1, 1, 2, 2, 0, 0, 1, 2, 1, 0, 0, 0])

In [8]:
model = Sequential([
    # embeddings can be added for when we want to represent sequences of multiple trits
    # Embedding(input_dim=1000, output_dim=64),
    LSTM(128, input_shape=(size, 1)),
    Dense(3, activation="softmax")
])
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [9]:
model.fit(X_train, y_train, epochs=25, batch_size=1, verbose=1)

Epoch 1/25
40/40 [==============================] - 1371s 35s/step - loss: 1.1421 - accuracy: 0.2500
Epoch 2/25
40/40 [==============================] - 1578s 39s/step - loss: 1.1090 - accuracy: 0.4250
Epoch 3/25
40/40 [==============================] - 1627s 41s/step - loss: 1.0844 - accuracy: 0.4250
Epoch 4/25
40/40 [==============================] - 1701s 43s/step - loss: 1.0887 - accuracy: 0.4250
Epoch 5/25
40/40 [==============================] - 1695s 42s/step - loss: 1.0954 - accuracy: 0.4250
Epoch 6/25
40/40 [==============================] - 1712s 43s/step - loss: 1.0844 - accuracy: 0.4250
Epoch 7/25
40/40 [==============================] - 1729s 43s/step - loss: 1.0971 - accuracy: 0.4250
Epoch 8/25
40/40 [==============================] - 1789s 45s/step - loss: 1.0967 - accuracy: 0.4250
Epoch 9/25
40/40 [==============================] - 1729s 43s/step - loss: 1.0860 - accuracy: 0.4250
Epoch 10/25
40/40 [==============================] - 1718s 43s/step - loss: 1.0864 - accura

In [12]:
model.save('thesis_sequence_initial.k5')

INFO:tensorflow:Assets written to: thesis_sequence_initial.k5\assets


INFO:tensorflow:Assets written to: thesis_sequence_initial.k5\assets


In [6]:
model = tf.keras.models.load_model('thesis_sequence_initial.k5')

In [12]:
y_pred = model.predict(x_test, batch_size=1, verbose='1')

In [13]:
print(y_pred)

[[0.31872442 0.2630343  0.41824135]
 [0.30524963 0.27286458 0.42188573]
 [0.30527455 0.2728458  0.42187962]
 [0.3009039  0.2630213  0.43607485]
 [0.30527455 0.2728458  0.42187962]
 [0.30527455 0.2728458  0.42187962]
 [0.31891906 0.2630189  0.41806203]
 [0.30818987 0.27083635 0.42097378]
 [0.30525747 0.27286273 0.42187983]
 [0.30527043 0.2728345  0.42189512]]
